# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

desc "Android Debug Build"
lane :android_debug do
  ionic(
    platform: 'android',
    prod: true,
    release: false
  )
end

desc "Android Release Build"
lane :android_release do
  ionic(
    platform: 'android',
    prod: true,
    release: true
  )
end